stages:
  download:
    cmd: python -m art_style_classifier.commands download_data --use_dvc=true
    deps:
      - art_style_classifier/data/download.py
      - art_style_classifier/commands.py
    params:
      - data
    outs:
      - data/raw/wikiart
    metrics:
      reports/download_metrics.json:
        cache: false
  prepare:
    cmd: python scripts/prepare_data.py
    deps:
      - data/raw/wikiart
      - scripts/prepare_data.py
    params:
      - data
    outs:
      - data/processed/train
      - data/processed/val
      - data/processed/test
      - data/processed/label_encoder.pkl
    metrics:
      reports/preparation_metrics.json:
        cache: false
  train:
    cmd: python scripts/train_model.py
    deps:
      - data/processed/train
      - data/processed/val
      - scripts/train_model.py
    params:
      - model
      - training
      - logging
    outs:
      - models/best_model.pth
      - models/last_model.pth
    metrics:
      reports/training_metrics.json:
        cache: false
      reports/validation_metrics.json:
        cache: false
  evaluate:
    cmd: python scripts/evaluate_model.py
    deps:
      - data/processed/test
      - models/best_model.pth
      - scripts/evaluate_model.py
    params:
      - model
    outs:
      - reports/test_predictions.csv
    metrics:
      reports/test_metrics.json:
        cache: false
      reports/confusion_matrix.png:
        cache: false
